#!/bin/bash
set -e
for config_file in {/cfg/,}{makepkg,pacman}.conf; do
    [[ -f $config_file ]] && sudo cp --target-directory=/etc "$config_file"
done
[[ -f PKGBUILD ]] && source PKGBUILD
sudo pacman -Syu --noconfirm --needed "${depends[@]}" "${makedepends[@]}" "${checkdepends[@]}"
