#!/bin/bash
set -e
bindir=$(dirname "$0")
${CRE:-docker} image pull "${CRE_IMAGE:-archlinux-base-devel}"
${CRE:-docker} image build --no-cache --tag "${CRE_IMAGE:-archlinux-base-devel}" "$bindir/base-devel"
